--Generated By msgid-gen-lua Do not Edit
local c2sConfig = {
	[778] = (require("Net.Protol.GateProtocol_pb")).C2GLoginTo,
}

local s2cConfig = {
	[778] = (require("Net.Protol.GateProtocol_pb")).G2CLoginTo,
	[1546] = (require("Net.Protol.GateProtocol_pb")).G2CSyncKey,
	[257] = (require("Net.Protol.LoginProtocol_pb")).LoginError,
}

return {
	C2S = c2sConfig,
	S2C = s2cConfig,
}
